#!/usr/bin/python

eventIdMap = {
    "network service modified": 215,
    "halo logout": 414,
    "daemon compromised": 712,
    "authorized ips modified": 905,
    "server group deleted": 427,
    "configuration policy created": 506,
    "alert profile created": 701,
    "server access scan requested": 812,
    "local account deleted (linux only)": 705,
    "special events policy created": 708,
    "daemon version changed": 713,
    "automatic server access scanning enabled": 802,
    "alert profile modified": 703,
    "daemon self-verification scheduled modfied": 909,
    "file integrity monitoring scan requested": 103,
    "automatic software vulnerability management scan schedule modified": 600,
    "automatic configuration scanning disabled": 501,
    "special events policy deleted": 709,
    "halo backup codes generated": 402,
    "configuration policy deleted": 507,
    "halo login failure": 409,
    "automatic server access scan schedule modified": 800,
    "halo password recovery requested": 400,
    "network service deleted": 213,
    "file integrity object signature changed": 127,
    "file integrity policy assigned": 105,
    "software vulnerability scan exception expired": 605,
    "software vulnerability detected": 603,
    "halo user account unlocked": 423,
    "alert profile unassigned": 704,
    "server missing": 719,
    "halo user account locked": 422,
    "server shutdown": 724,
    "multiple root accounts detected (linux only)": 715,
    "automatic software vulnerability management scanning enabled": 602,
    "local account activation requested": 804,
    "local account created (linux only)": 714,
    "server un-retired": 725,
    "automatic file integrity scan schedule modified": 100,
    "alert profile assigned": 700,
    "api secret key viewed": 904,
    "local account modification requested": 809,
    "halo user deactivated": 912,
    "halo user reactivated": 916,
    "configuration scan requested": 513,
    "api key created": 901,
    "special events policy unassigned": 711,
    "software vulnerability scan exception created": 604,
    "file integrity object missing": 126,
    "file integrity baseline expired": 120,
    "daily status email scheduled modified": 910,
    "ghostports session close": 316,
    "halo password recovery failed": 418,
    "halo password recovery success": 420,
    "halo password changed": 415,
    "api key modified": 903,
    "automatic file integrity scanning enabled": 102,
    "server firewall modified locally": 706,
    "configuration policy exported": 508,
    "halo firewall policy assigned": 201,
    "daemon self-verification scan requested": 401,
    "configuration policy assigned": 505,
    "halo firewall policy deleted": 204,
    "halo user modified": 914,
    "configuration rule matched": 503,
    "file integrity policy deleted": 109,
    "configuration policy imported": 509,
    "software vulnerability scan requested": 606,
    "file integrity policy created": 107,
    "network service added": 211,
    "file integrity baseline failed": 121,
    "daemon heartbeat interval modified": 906,
    "automatic file integrity scanning disabled": 101,
    "file integrity policy unassigned": 113,
    "server retired": 723,
    "file integrity policy imported": 129,
    "alert profile deleted": 702,
    "file integrity policy modified": 111,
    "automatic software vulnerability management scanning disabled": 601,
    "automatic configuration scanning enabled": 502,
    "file integrity policy changed": 133,
    "ghostports expiration time modified": 911,
    "halo firewall policy unassigned": 208,
    "password configuration settings modified": 918,
    "file integrity exception created": 122,
    "ghostports login success": 306,
    "halo login success": 413,
    "server deleted": 717,
    "new server": 716,
    "local account deactivation requested": 808,
    "file integrity baseline": 115,
    "automatic configuration scan schedule modified": 500,
    "halo password recovery request failed": 419,
    "ghostports provisioning": 311,
    "local account creation requested": 806,
    "special events policy assigned": 707,
    "master account linked": 917,
    "server moved to another group": 721,
    "server firewall restore requested": 216,
    "server restarted": 722,
    "halo firewall policy created": 210,
    "daemon self-verification enabled": 908,
    "file integrity exception deleted": 123,
    "server group added": 425,
    "halo user re-invited": 915,
    "ghostports login failure": 305,
    "file integrity object added": 125,
    "api key deleted": 902,
    "file integrity baseline deleted": 119,
    "daemon registration key regenerated": 900,
    "file integrity policy exported": 128,
    "daemon self-verification disabled": 907,
    "local account ssh keys update requested": 811,
    "file integrity exception expired": 124,
    "server ip address changed": 718,
    "halo session timeout": 421,
    "configuration policy unassigned": 512,
    "configuration policy modified": 510,
    "special events policy modified": 710,
    "automatic server access scanning disabled": 801,
    "halo firewall policy modified": 206,
    "file integrity re-baseline": 131,
    "halo user invited": 913,
}

'''These events should have an elevated rel/prio to
 ensure that they become alarms
'''

eventIdsToElevate = (
    126,
    127,
    400,
    409,
    418,
    422,
    603,
    604,
    706,
    714,
    715,
    716,
    719,
    801
)
